# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
